server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: master-info
          uri: http://localhost:8081
          predicates:
            - Path=/users/**, /companies/**, /machines/**, /products/**, /progresses/**, 
        - id: production
          uri: http://localhost:8082
          predicates:
            - Path=/commands/**, /workjobs/**, 
        - id: purchase
          uri: http://localhost:8083
          predicates:
            - Path=/purchaseOrders/**, /purchaseIns/**, 
        - id: delivery
          uri: http://localhost:8084
          predicates:
            - Path=/productOrders/**, /productDeliveries/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: master-info
          uri: http://masterInfo:8080
          predicates:
            - Path=/users/**, /companies/**, /machines/**, /products/**, /progresses/**, 
        - id: production
          uri: http://production:8080
          predicates:
            - Path=/commands/**, /workjobs/**, 
        - id: purchase
          uri: http://purchase:8080
          predicates:
            - Path=/purchaseOrders/**, /purchaseIns/**, 
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/productOrders/**, /productDeliveries/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
